### ISSUE TITLE
dieter compilation is incredibly slow

### ISSUE THREAD

**Issue by pbiggar** [edgecase/dieter#12]
Our web site has become incredibly slow since using dieter. Most assets feel like they're being compiled on every request, and can take 20 seconds in some cases. I'm filing a couple of meta issues, which I hope should help solve them.

**Comment by bostonaholic** [comment]
How are you deploying and starting your app? We have a clojure app running on Heroku's Cedar stack and here are some tips that greatly increased the speed:
1. Flag dieter to run in production mode via `(swap! dieter-config assoc :cache-mode :production)`
2. In the `project.clj` use `:jvm-opts ["-server"]` - this will optimize the jvm for long running server processes

**Comment by pbiggar** [comment]
Thanks!, though we already use production mode and the server setting. I've outlined what dieter needs in other issues - this issue is just to follow the high-level problem.

**Comment by jxa** [comment]
Closing this because of other specific issues being tracked
