### ISSUE TITLE
dieter should use v8 instead of rhino

### ISSUE THREAD

**Issue by pbiggar** [edgecase/dieter#15]
Rhino is incredibly slow, and v8 is not. I think this might be quite a challenge though - I did a quick search for java packages using v8, and it seems to be pretty damn difficult.

This manifests in two ways: during development, page reload can often take 10 seconds for a single asset. Since we recompile each asset each page view, this is hard to avoid. Secondly, the first requests on a fresh web server are very slow.

**Comment by jxa** [comment]
http://code.google.com/p/jav8/ seems somewhat promising, but I couldn't get the hello world to run. I'd love to use v8 but it seems like we would have serious challenges with native dependencies and making it cross-platform even if we got it to run locally.

**Comment by ivanstojic** [comment]
As Paul already knows, it's not that difficult :) You should follow either my own clj-v8 fork from which Paul / circleci pulls the code, or just follow his clj-v8 for the "official and stable" version. Right now we're working on getting the support completed for three platforms: 32 and 64 bit Linux and for 64 bit OS X. Adding extra platforms shouldn't be (too) difficult either if someone can provide ssh access to a development machine of the chosen platform.

**Comment by pbiggar** [comment]
Done, should go out in 0.3.0
