### ISSUE TITLE
dieter should generate dependency information

### ISSUE THREAD

**Issue by pbiggar** [edgecase/dieter#16]

**Comment by jxa** [comment]
+1

**Comment by jxa** [comment]
I've started work on this in the [asset-cache](https://github.com/edgecase/dieter/tree/asset-cache) branch

**Comment by pbiggar** [comment]
I renamed the issue, because I think it's indicative of a larger problem about dependencies.

We use lein dieter-precompile, and we run into frequent problems. When running tests, we use production mode, so it compiles files, but only if they dont exist. What happens when we run the tests again? They dont get regenerated, even if the source files have been changed. Lots of subtle bugs!

The solution to this is the same as for not regenerating files that dont need it: keep track of dependency information. I propose that when we generate a json file providing a map from a sha1 to a generated file. If we see the sha1 again, we can reuse it.

What if the compiled files are stale? Well then, we would see that the current file is not the same as the sha1 in the dependency, and we would regenerate it.

**Comment by ivanstojic** [comment]
Since it seems that @jxa fell asleep, I'll be trying to tackle this. As the rest of my work, I'll be attacking this on the v8 branch, hopefully it'll get merged into main when the rest of the changes settle down.

**Comment by ivanstojic** [comment]
Actually, I think @pbiggar is right - there are some deeper problems. For instance, in my latest version, the precompile output filename is broken:

```
~/Documents/Programming/circleci/dieter/test-projects/t3 $ lein dieter-precompile          
...                                                                                        
~/Documents/Programming/circleci/dieter/test-projects/t3 $ ls resources/asset-cache/assets/
js/  scripts.js-4a1f1a8f98700e7c3f8578c6b9dbaffe.dieter
```

And after accessing the doc through the Ring middleware, this shows up:

```
~/Documents/Programming/circleci/dieter/test-projects/t3 $ ls resources/asset-cache/assets/
js/  scripts-4a1f1a8f98700e7c3f8578c6b9dbaffe.js  scripts.js-4a1f1a8f98700e7c3f8578c6b9dbaffe.dieter
```

Either I misunderstand the Dieter file naming rules, or the precompile is currently broken.

**Comment by pbiggar** [comment]
The main aim is solved here: caching previously compiled assets is now done in-memory, and parts of manifests and untouched files are typically served from memory (based on a timestamp). It would be trivial to do it on disk, but since dieter is fast now, I don't think that's necessary.
