### ISSUE TITLE
I believe there is a bug in dieter's caching of compiled assets

### ISSUE THREAD

**Issue by pbiggar** [edgecase/dieter#17]
I havent investigated this fully yet, but our web logs show that even days after being compiled, assets are still taking 20 seconds to be served, implying that dieter is recompiling them in each request.

**Comment by jxa** [comment]
Are you using the link-to-asset helper to generate your paths?
Please update with details of cache failures.

**Comment by pbiggar** [comment]
I looked into this, and I believe I was wrong the first time. I see a lot of recompilation, but I think that's because we deploy so much. I think `lein dieter-precompile` is the solution.
